[window]
padding = { x = 10, y = 10 }
dynamic_padding = false
opacity = 0.95

[font]
size = 14.0
normal = { family = "FantasqueSansM Nerd Font", style = "Regular" }
italic = { family = "FantasqueSansM Nerd Font", style = "Italic" }
bold = { family = "FantasqueSansM Nerd Font", style = "Regular" }
bold_italic = { family = "FantasqueSansM Nerd Font", style = "Italic" }

[cursor]
style = { shape = "Beam", blinking = "Off" }
thickness = 0.1

[env]
SHELL = "/usr/bin/zsh"

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#222222"
foreground = "#f0f0f0"

[colors.cursor]
text = "#222222"
cursor = "#f0f0f0"

[colors.selection]
text = "#f0f0f0"
background = "#3a3a3a"

[colors.normal]
black   = "#2e2e2e"
red     = "#c06060"
green   = "#90a959"
yellow  = "#f2ae49"
blue    = "#6a9fb5"
magenta = "#aa759f"
cyan    = "#75b5aa"
white   = "#d0d0d0"

[colors.bright]
black   = "#4e4e4e"
red     = "#d18f8f"
green   = "#a7bd68"
yellow  = "#ffcc66"
blue    = "#82b3c9"
magenta = "#c69ac6"
cyan    = "#9ad1b4"
white   = "#f0f0f0"
